[package]
name = "derpibooru-downloader"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
const_format = "0.2"
dirs = "6"
log = "0.4"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_path_to_error = "0.1"
simplelog = "0.12"
toml = "0.9"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
print_stdout = "deny"
print_stderr = "deny"
panic = "warn"
unwrap_used = "warn"
expect_used = "warn"
indexing_slicing = "warn"
