[package]
name = "derpibooru-downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
simplelog = "0.12"
anyhow = "1.0"
const_format = "0.2"

# debug only
serde_json = "1.0"
serde_path_to_error = "0.1"

[dev-dependencies]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
print_stdout = "deny"
print_stderr = "deny"
unwrap_used = "warn"
